---
- name: Install java and net-tools
  hosts: nexus_server
  become: true
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install Java 8 and net-tools
      apt:
        pkg:
          - openjdk-8-jre-headless
          - net-tools

- name: Download and unpack Nexus installer
  hosts: nexus_server
  become: true
  tasks:
    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}
    - name: Download nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.47.1-01-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Unarchive tar file
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: Find nexus module
      find:
        paths: /opt
        file_type: directory
        patterns: 'nexus*'
      register: dir_name    
    - name: Changing name of dir
      shell: mv {{dir_name.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists
      register: app_status
    - debug: msg={{app_status}}

- name: Creating group and user for nexus
  hosts: nexus_server
  become: true
  tasks: 
    - name: Create group
      group:
        name: nexus
        state: present
    - name: Add user
      user:
        name: nexus
        group: nexus
    - name: Make nexus owner of nexus directory
      file:
        path: /opt/nexus
        state: directory
        recurse: yes
        owner: nexus
        group: nexus
    - name: Make nexus owner of sonatype directory
      file:
        path: /opt/sonatype-work
        state: directory
        recurse: yes
        owner: nexus
        group: nexus

- name: Start nexus with nexus user
  hosts: nexus_server
  become: true
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^run_as_user=""'
        line: run_as_user="nexus"
    - name: run command for nexus
      command: /opt/nexus/bin/nexus start

- name: Verify nexus running
  hosts: nexus_server
  tasks:
    - name: Check process status
      shell: ps aux | grep nexus
      register: process_stat
    - debug: msg={{process_stat}}
    - name: Wait 1 minute
      pause:
        minutes: 1
    - name: Check port number
      shell: netstat -lnpt
      register: port_number_stat
    - debug: msg={{port_number_stat}}
  
